f1_dbt:
  target: dev
  
  outputs:
    # Development (Local ClickHouse)
    dev:
      type: clickhouse
      schema: staging # Namespace for dev work
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', '') }}"
      secure: false
      verify: false
      connect_timeout: 10
      cluster_mode: false
      threads: 4  # Parallel model builds
      
    # CI/Testing (Ephemeral schemas)
    ci:
      type: clickhouse
      schema: "ci_{{ env_var('CI_JOB_ID', 'local') }}"  # Unique per CI run
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: 8123
      user: default
      password: ""
      secure: false
      verify: false
      connect_timeout: 10
      
    # Production
    prod:
      type: clickhouse
      schema: "{{ env_var('DBT_SCHEMA', 'silver') }}"  # Default production schema
      host: "{{ env_var('CLICKHOUSE_HOST_PROD', 'clickhouse') }}"
      port: 8123
      user: "{{ env_var('CLICKHOUSE_USER_PROD', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD_PROD', '') }}"
      secure: "{{ env_var('CLICKHOUSE_SECURE', 'false') | as_bool }}"
      verify: true
      connect_timeout: 30
      cluster_mode: false
      threads: 8