FROM apache/airflow:3.1.7

# 2. Switch to root to copy the requirements file
USER root

# Copy the requirements.txt generated by 'uv export'
COPY requirements.txt /requirements.txt

# 3. Switch back to airflow user to install packages
# This ensures libraries are found in the default airflow path
USER airflow

# Install dependencies using the pinned file
# --no-deps is used because requirements.txt is a full, universal resolution from uv.
# This bypasses strict pip resolution checks for transitive conflicts (e.g. Starlette)
# that are already handled by our uv overrides.
RUN pip install --no-cache-dir --no-deps -r /requirements.txt